name: cron-schedule-workflow
on:
<<<<<<< HEAD
  pull_request:
  # schedule:
  #   - cron: "0/10 * * * *"
=======
  schedule:
    - cron: "0/10 * * * *"
>>>>>>> main
jobs:
  get-basic-info:
    runs-on: ubuntu-latest
    steps:
      - name: Get directory info
        run: |
          pwd 
          ls
      - name: Get git details
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
