name: cron-schedule-workflow
on:
  schedule:
    - cron: "0/5 * * * *"
jobs:
  get-basic-info:
    runs-on: ubuntu-latest
    steps:
      - name: Get directory info
        run: |
          echo "Current directory : \n" && pwd
          echo "Current folders and files : \n" && ls -a 
      - name: Get git details
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
