name: Testing env variables
on:
  push:
    branches:
      - "main"
env:
  WF_ENV: Available to all jobs
jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available to all steps in log-env job
    steps:
      - name: Log Environment Variables
        env:
          STEP_ENV: Available in this step only
        run: |
          echo "WF_ENV ${WF_ENV}"
          echo "JOB_ENV ${JOB_ENV}"
          echo "STEP_ENV ${STEP_ENV}"
      - name: Log env2
        run: |
          echo "WF_ENV ${WF_ENV}"
          echo "JOB_ENV ${JOB_ENV}"
          echo "STEP_ENV ${STEP_ENV}"
  log-default-env:
    runs-on: ubuntu-latest
    steps:
      - name: Log default variables
        run: |
          echo "HOME ${HOME}"
          echo "GITHUB_WORKFLOW ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION ${GITHUB_ACTION}"
          echo "GITHUB_REPOSITORY ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA ${GITHUB_SHA}"
          echo "GITHUB_REF ${GITHUB_REF}"
          echo "GIThUB_TOKEN" ${{ github.token }}



    