name: Create PR label
on:
  pull_request:
    branches:
      - main
jobs:
  create-label:
    runs-on: ubuntu-latest
    steps:
      - name: Adding comment in the PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'CF Pages Deploy Preview: Hello World
            })
  
     