name: 'Sample commands'
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello World this is sample"
      - name:  multiline-script
        run: |
          node -v
          npm -v
  basic-python-commands:
    runs-on: ubuntu-latest
    needs: [run-shell-commands]
    steps:
     - name: Basic commands
       run: pwd
     - name: Python commands
       run: |
         import platform
         print(platform.processor())
         print('Hello world')
       shell: python
  # run-windows-commands:
  #   runs-on: windows-latest
  #   needs: [basic-python-commands]
  #   steps:
  #     - name: Directory powershell
  #       shell: powershell
  #       run: Get-location
  #     - name: Directory bash
  #       shell: bash
  #       run: pwd

        
