name: 'Sample commands'
on: [push, pull_request]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello World this is sample"
      - name:  multiline-script
        run: |
          node -v
          npm -v
  job2:
    runs-on: ubuntu-latest
    steps:
     - name: Basic commands
       run: pwd
     - name: Python commands
       run: |
         import platform
         print(platform.processor())
         print('Hello world')
       shell: python
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Directory powershell
        shell: powershell
        run: Get-location
      - name: Directory bash
        shell: bash
        run: pwd

        
